version: '3.9'

services:
  explorer:
    container_name: explorer
    build:
      context: .
      target: builder
    image: explorer
    restart: on-failure
    networks:
      - mynet
    ports:
      - 1323:1323
    environment:
      - HTTP_PORT=${HTTP_PORT:-1323}
      - SIGNING_KEY=${SIGNING_KEY:-strongPassword}
      - TOKEN_TTL=${TOKEN_TTL:-86400}
      - STEP=${STEP:-1000}
      - NODE=${NODE:-https://testnet-tezos.giganode.io/chains/main/blocks/}
      - POSTGRES_HOST=${POSTGRES_HOST:-pgdb}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSOWRD:-mysecretpassword}
      - POSTGRES_DB=${POSTGRES_DB:-blockchain_explorer}
      - PGDATA=${POSTGRES_DATA:-/var/lib/postgresql/data/}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-chdb}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8123}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-blocks}
    volumes:
      - ./:/app
    depends_on:
      - postgres_db
      - clickhouse_db

  postgres_db:
    container_name: pg_db
    hostname: pgdb
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSOWRD:-mysecretpassword}
      - POSTGRES_DB=${POSTGRES_DB:-blockchain_explorer}
      - PGDATA=${POSTGRES_DATA:-/var/lib/postgresql/data/}
    ports:
      - 5432:5432
    restart: on-failure
    networks:
      - mynet
    volumes:
      - pgvolume:/var/lib/postgresql/data/
    command: [ "postgres", "-c", "log_statement=all" ]

  clickhouse_db:
    container_name: ch_db
    hostname: chdb
    image: yandex/clickhouse-server
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-blocks}
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - chvolume:/var/lib/clickhouse
      # - ./internal/storage/init-defaults.sh:/docker-entrypoint-initdb.d/init-defaults.sh:ro
    networks:
      - mynet

volumes:
  pgvolume: null
  chvolume: null
networks:
  mynet:
    driver: bridge
