address: ":1323"

auth:
  signing_key: "strongPassword"
  token_ttl: 86400

postgres:
  pg_host: "localhost"
  pg_port: 5432
  pg_user: "postgres"
  pg_pass: "1234"
  pg_db:   "blockchain_explorer"
  pg_ssl:  "disable"

clickhouse:
  ch_host:  "localhost"
  ch_port:  8123
  ch_db:    "blocks"
  ch_debug: "true"

explorer:
  totalWorkers: 10
  crawlerStartPos: 700000
  step: 1000
  contract: "KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn"
  node: "https://testnet-tezos.giganode.io/chains/main/blocks/"
